name: '⚙️ CI/CD Pipeline'
on: 
  push:
    branches:
      - main

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  config:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Trying stuff out
        run: echo "Not doing anything super seriously"
  cd:
    needs: config
    uses: ./.github/workflows/cd.yml