name: '❤️‍🩹 Continuous Integration (CI)'

on:
  push:
      branches:
          - main
  workflow_call:

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Set up Python
            uses: actions/setup-python@v3
            with:
              python-version: '3.11.9'

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
    lint:
        needs: setup
        runs-on: ubuntu-latest
        steps:
          - name: Lint code
            run: |
              pip install flake8
              flake8 .
    test:
        needs: setup
        runs-on: ubuntu-latest
        steps:
          - name: Run tests
            run: echo "Run python pytests here!"